# Use root/example as user/password credentials

version: '3.8'

services:

  adminer:
    image: adminer
    ports:
      - '8080:8080'

  db:
    image: mysql:latest
    env_file: .env
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '3306:3306'
